# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.

name: spack
title: Spack
icon: data/spack-logo.svg
version: 0.20.1
adopt-info: spack
summary: A flexible package manager that supports multiple configurations.
description: |
  Spack is a multi-platform package manager that builds and installs multiple
   versions and configurations of software. It works on Linux, macOS, and many
   supercomputers. Spack is non-destructive: installing a new version of a
   package does not break existing installations, so many configurations of the
   same package can coexist.

  Spack offers a simple "spec" syntax that allows users to specify versions and
   configuration options. Package files are written in pure Python, and specs
   allow package authors to write a single script for many different builds of
   the same package. With Spack, you can build your software all the ways you
   want to.
license: Apache-2.0
website: "https://spack.io/"

base: core22
grade: stable
confinement: classic
compression: lzo
architectures:
  - build-on: amd64

apps:
  spack:
    command: bin/spack

parts:
  spack:
    plugin: dump
    source: >-
      https://github.com/spack/spack/releases/download/v${SNAPCRAFT_PROJECT_VERSION}/spack-${SNAPCRAFT_PROJECT_VERSION}.tar.gz
    build-snaps:
      - yq
    override-build: |
      craftctl default

      set -eux
      # Update default spack configuration.
      # This configuration can be overridden per machine in /etc/spack,
      # or can be overridden per-user in ~/.spack.
      yq -i '
        .config.install_tree.root = "/opt/spack" |
        .config.template_dirs[0] = "/opt/spack/share/spack/templates" |
        .config.license_dir = "/opt/spack/etc/spack/licenses" |
        .config.source_cache = "/opt/spack/var/spack/cache"
      ' etc/spack/defaults/config.yaml
      yq -i '
        .modules.default.roots.tcl = "/opt/spack/share/spack/modules" |
        .modules.default.roots.lmod = "/opt/spack/share/spack/lmod"
      ' etc/spack/defaults/modules.yaml
